In [7]:
import numpy as np
x=np.array([1, 2, 3, 4]) #1차원 행렬(백터) 생성
print(x)

[1 2 3 4]


In [9]:
y = np.array([[2,3,4], [1,2,5]]) #2차원 행렬 생성
print(y)

[[2 3 4]
 [1 2 5]]


In [10]:
print(type(y))

<class 'numpy.ndarray'>


In [12]:
# 0~9까지를 원소로하는 백터를 ndarray로 생성가능
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 1~9까지를 원소로하는 백터를 ndarray로 생성가능
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# 1~9까지 원소 중에서 1부터 2칸씩 건너뛴 수를 원소로 하는 백터를 ndarray로 생성
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [17]:
# 5~100까지 원소 중에서 5부터 5칸씩 건너뛴 수를 원소로 하는 백터를 ndarray로 생성
np.arange(5,101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [18]:
#모든 원소의 값이 1로 구성된 4행 5열의 2차원 행렬
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#모든 원소의 값이 1로 구성된 3행 4열의 2개 3차원 행렬
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
#모든 원소의 값이 0로 구성된 2행 3열의  2차원 행렬
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((2, 3, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [22]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [23]:
np.full((3, 4, 2), 7)

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [27]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [31]:
x = np.arange(1, 16)
print(x)
x.reshape(3, 5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
x = np.arange(1, 16)
print(x)
x.reshape(5, 3, 1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [33]:
np.random.rand(2,3)

array([[0.96783306, 0.43344608, 0.94418019],
       [0.69059505, 0.05575142, 0.25033472]])

In [34]:
np.random.rand(2)

array([0.91133052, 0.62005976])

In [35]:
np.random.rand(10)

array([0.11285784, 0.0048235 , 0.89163848, 0.8103341 , 0.07327458,
       0.60022608, 0.01908829, 0.00384403, 0.96715838, 0.50945652])

In [36]:
np.random.rand(2,5,3)

array([[[0.41576923, 0.60019392, 0.58150747],
        [0.86944772, 0.23830536, 0.90423404],
        [0.28033411, 0.64015676, 0.03746362],
        [0.73964936, 0.75757083, 0.65484879],
        [0.29388196, 0.85445583, 0.54391096]],

       [[0.48968292, 0.49571803, 0.17664693],
        [0.07485625, 0.90291428, 0.09989913],
        [0.41197569, 0.26937385, 0.7410977 ],
        [0.02788919, 0.21262112, 0.86618801],
        [0.293493  , 0.33847886, 0.14593491]]])

In [37]:
np.random.randn(3,4,2)

array([[[ 0.05691246,  0.21531014],
        [ 0.41759201, -0.86445099],
        [-0.47982076,  1.13540165],
        [-0.48335688,  0.33771131]],

       [[ 1.95541769,  0.8025249 ],
        [-1.88287296, -0.40827717],
        [ 0.61955777, -0.42142979],
        [ 0.11066345,  1.20012217]],

       [[-0.20123997, -0.48670668],
        [-1.19924531, -0.79550776],
        [-0.35917542,  0.71379782],
        [-0.45997939, -0.48734462]]])

In [38]:
np.random.randn(5)

array([-0.81830417, -0.09573586,  0.73026533,  0.83504709, -0.91337372])

In [40]:
np.random.randint(1, 100, size=(3,5))

array([[62, 37, 43, 30, 41],
       [84, 56, 51, 37, 72],
       [63, 37, 90, 13, 65]])

In [42]:
np.random.randint(1, 100, size=(2,3,5))

array([[[16, 78, 19, 28, 39],
        [89, 19, 62, 79, 21],
        [69, 29, 28, 16, 95]],

       [[47, 18, 95, 14, 27],
        [71, 35, 13, 19, 16],
        [97, 24, 29, 68, 44]]])

In [43]:
np.random.seed(0)

In [44]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [45]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [46]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [47]:
np.random.seed(0)

In [48]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [49]:
np.random.choice(100, size=(3,4))

array([[39, 87, 46, 88],
       [81, 37, 25, 77],
       [72,  9, 20, 80]])

In [50]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2,2))

array([[1.5, 4.9],
       [1. , 3. ]])

In [51]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2,2), replace=False)

array([[2.6, 3. ],
       [4.9, 2. ]])

In [52]:
np.random.uniform(1.0, 3.0, size=(4,5))

array([[2.35775906, 2.44126531, 2.16403958, 2.07474646, 2.51723125],
       [1.21181521, 1.94720084, 1.37266469, 2.47383635, 1.43310071],
       [1.27043635, 1.64828202, 1.29934973, 1.44464278, 1.77297796],
       [2.80519695, 1.89989998, 2.22612692, 2.80469717, 1.1985607 ]])

In [53]:
np.random.normal(size=(4,5))

array([[ 0.06731083,  0.20649884, -0.45688133, -1.05997576,  0.61495732],
       [ 1.42966077, -0.21195226, -0.08033726,  0.40539778,  0.11860659],
       [ 1.25441407,  1.41910204, -0.74385608, -2.5174371 , -1.50709602],
       [ 1.14907613, -1.19357825,  1.14104245,  1.50944508,  1.06777513]])

In [54]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
x[0]

0

In [56]:
x[-1]

9

In [57]:
x[3] = 100

In [58]:
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [60]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
x[0]

array([0, 1, 2, 3, 4])

In [62]:
x[1]

array([5, 6, 7, 8, 9])

In [63]:
x[0,2]

2

In [66]:
x = np.arange(36).reshape(3, 4, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [67]:
x[1,2]

array([18, 19, 20])

In [68]:
x[1,2,1]

19

In [70]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [73]:
x = np.arange(54).reshape(2, 9, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [74]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [76]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.86510256 0.50896896 0.91672295 0.92115761 0.08311249]
 [0.27771856 0.0093567  0.84234208 0.64717414 0.84138612]
 [0.26473016 0.39782075 0.55282148 0.16494046 0.36980809]]


In [81]:
np.add(x,y)

array([[ 0.86510256,  1.50896896,  2.91672295,  3.92115761,  4.08311249],
       [ 5.27771856,  6.0093567 ,  7.84234208,  8.64717414,  9.84138612],
       [10.26473016, 11.39782075, 12.55282148, 13.16494046, 14.36980809]])

In [82]:
x+y

array([[ 0.86510256,  1.50896896,  2.91672295,  3.92115761,  4.08311249],
       [ 5.27771856,  6.0093567 ,  7.84234208,  8.64717414,  9.84138612],
       [10.26473016, 11.39782075, 12.55282148, 13.16494046, 14.36980809]])

In [83]:
np.mean(y)

0.5108775422646494

In [84]:
z = np.random.randn(10)
z

array([ 0.22113881, -1.12305712, -1.05075796,  1.01207905,  1.54371643,
       -0.40211489,  0.8647491 , -0.22686923,  0.81116027,  0.28779461])

In [85]:
z>0

array([ True, False, False,  True,  True, False,  True, False,  True,
        True])

In [86]:
np.any(z>0)

True

In [87]:
np.all(z>0)

False

In [88]:
z=np.random.randn(10)
z

array([-0.53846816,  1.9084621 , -0.475776  ,  1.44073112, -1.14907568,
        0.80571455,  1.75610703,  0.97297991, -1.55111911,  0.19114348])

In [89]:
np.where(z>0, z, 0)

array([0.        , 1.9084621 , 0.        , 1.44073112, 0.        ,
       0.80571455, 1.75610703, 0.97297991, 0.        , 0.19114348])

10*13.5*10*100!!

11.4